# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

WORKDIR /app

# Upgrade pip and setuptools
RUN pip install --upgrade pip setuptools

# Copy the project files
COPY . /app

# Install the package using the pyproject.toml (PEP 517/518)
RUN pip install .

# Expose port if needed (uncomment if your server listens on a port)
# EXPOSE 8000

# Run the MCP server
CMD ["python", "-m", "src.opendota_server.server"]
